spring.application.name=sfp-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/financeiro_db
spring.datasource.username=${DB_USERNAME:postgres} #usar variáveis de ambiente
spring.datasource.password=${DB_PASWWORD:postgres} #usar variáveis de ambiente
spring.datasource.driver-class-name=org.postgresql.Driver

#Desativando o Hibernate temporariamente
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Configuracoes JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

#Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration